[build]
  publish = "."  # Thư mục gốc chứa file HTML

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Frame-Options = "DENY"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200